"""
Seed the paper-trading journal from the walk-forward OUT-OF-SAMPLE tape.
========================================================================

Purpose
-------
Produce an honest, ready-to-show trade journal: a realistic book of CLOSED
paper trades the strategy generated **out-of-sample** (point-in-time — at each
date the engine used only models trained on prior data), sized by the
risk-based model in `sizing.py`.

This is NOT a live-accumulated book and must never be presented as one. Rows are
tagged `source='walkforward'` so they are distinct from the live A/B arms
(`ab_mode` in {pooled, gated}). The honest framing for the mentor:
  "out-of-sample walk-forward track record (no lookahead), sized by the risk
   model — plus a live book now accumulating the same in real time."

Method (mirrors how a real book behaves)
----------------------------------------
* Source tape: `pooled_trades.json` (the pooled-mode OOS signals).
* Trade only LONG/SHORT signals (|z| ≥ 0.5) on the live tradeable universe
  (drops the brent/wti M3-M6 laggards — `live_ranker.TUNED_EXCLUDED_SPREADS`).
* Walk chronologically; hold ONE position per spread at a time (no re-entry
  until the open one closes) — avoids unrealistic daily overtrading.
* **Exit simulator** (Phase 4 fix — 2026-06-17):
  Every trade is walked daily-forward through `exit_sim.simulate_one` with
  the *live* tuned exit rule: TP = halfway-to-fair, SL = 2.5 × resid_std,
  max-hold = 20 trading days (capped by the walk-forward FORWARD_DAYS).
  The close_reason can now be 'target' (TP hit), 'stop' (SL hit),
  'time_stop_20d' (neither hit by horizon), or 'scratch' (degenerate TP on
  the wrong side of entry, see exit_sim.py docstring).
  Realised P&L = exit_price minus entry × barrels (real dollars), where
  barrels comes from sizing.size_trade(spread, σ=resid_std, z).
  Prior bug: every trade was hardcoded as 'time_stop_20d' — the journal
  always showed 100% time-stops with the raw 20-day fwd_pnl.
* The live engine uses a 30d time-stop; the seed tape only carries 20d
  forward paths, so the seed honestly stops at 20d. We surface this in the
  reason string.

Run:
    python -m backend.research.seed_journal --months 6 --reset
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

_BACKEND = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if _BACKEND not in sys.path:
    sys.path.insert(0, _BACKEND)

import paper_trading as pt
from research import live_ranker, exit_sim
from research.sizing import size_trade, CONTRACT_MULTIPLIER, STOP_SIGMA
from research.spread_universe import build_spread_series

# Phase 4 (2026-06-17) — production tape switched to the global model. The
# `global_trades.json` is the OOS walk-forward output of the regime-as-feature
# coherent-quantile architecture (see models_global.py); the legacy
# pooled_trades.json was generated by the broken per-cell models the audit
# exposed. Pass --tape pooled to fall back if needed.
_TAPE_GLOBAL = Path(__file__).parent.parent / "data" / "research" / "global_trades.json"
_TAPE_POOLED = Path(__file__).parent.parent / "data" / "research" / "pooled_trades.json"
_TAPE = _TAPE_GLOBAL if _TAPE_GLOBAL.exists() else _TAPE_POOLED


# Map exit_sim's atomic reasons → display strings the dashboard uses.
_CLOSE_REASON_MAP = {
    "TP":      "target",
    "SL":      "stop",
    "TIME":    "time_stop_20d",
    "SCRATCH": "scratch",
}


def _conviction(z: float) -> str:
    az = abs(z)
    if az >= 1.5:
        return "HIGH"
    if az >= 0.8:
        return "MODERATE"
    return "LOW"


def _iso(date_str: str) -> str:
    # tape dates are 'YYYY-MM-DD'; store as midnight UTC ISO for the journal.
    return f"{date_str}T00:00:00+00:00"


def seed(months: int = 6, reset: bool = True, brent_only: bool = True) -> dict:
    tape = json.load(open(_TAPE, encoding="utf-8"))
    last = max(r["date"] for r in tape if r.get("date"))
    cutoff = (datetime.strptime(last, "%Y-%m-%d") - timedelta(days=int(months * 30.5))).strftime("%Y-%m-%d")

    # Daily spread paths — needed by exit_sim.simulate_one to walk each trade
    # forward day-by-day and resolve TP/SL/time-stop properly.
    spreads = build_spread_series()
    paths = {sp: spreads[sp].dropna() for sp in spreads.columns}

    excluded = live_ranker.TUNED_EXCLUDED_SPREADS

    # Per-spread REALIZED volatility for risk-based sizing. Sizing the stop off
    # the model residual std (resid_std) over-sizes wildly — it's a tiny
    # in-sample number, so a 2.5σ stop is pennies and lots balloon. A real desk
    # sizes off the INSTRUMENT'S own volatility: here, the trailing 60-obs std of
    # the spread level, computed point-in-time (only dates ≤ entry).
    from collections import defaultdict
    series: dict[str, list[tuple[str, float]]] = defaultdict(list)
    for r in sorted(tape, key=lambda x: x.get("date", "")):
        if r.get("actual") is not None and r.get("spread"):
            series[r["spread"]].append((r["date"], float(r["actual"])))

    def _std(vals: list[float]) -> float:
        if len(vals) < 2:
            return 0.0
        m = sum(vals) / len(vals)
        return (sum((v - m) ** 2 for v in vals) / (len(vals) - 1)) ** 0.5

    # Per-spread long-run vol → a FLOOR so a transient flat patch can't collapse
    # σ and balloon the lot count (the source of the one $134k outlier).
    global_std = {sp: _std([v for _, v in arr]) for sp, arr in series.items()}

    def realized_vol(sp: str, date: str, win: int = 90) -> float | None:
        vals = [v for (dt, v) in series.get(sp, []) if dt <= date][-win:]
        if len(vals) < 10:
            return None
        floor = 0.5 * global_std.get(sp, 0.0)
        return max(_std(vals), floor) if floor > 0 else _std(vals)

    # Tape encodes side as BUY/SELL; the paper book stores LONG/SHORT.
    rows = [
        r for r in tape
        if r.get("direction") in ("BUY", "SELL")
        and r.get("spread") not in excluded
        and (not brent_only or str(r.get("spread", "")).startswith("brent"))
        and r.get("fwd_pnl") is not None
        and r.get("z") is not None
        and r.get("date", "") >= cutoff
    ]
    rows.sort(key=lambda r: r["date"])

    c = pt._conn()
    if reset:
        c.execute("DELETE FROM paper_legs")
        c.execute("DELETE FROM paper_trades")
        c.commit()

    open_until: dict[str, str] = {}
    n = 0
    reason_counts: dict[str, int] = {}
    for r in rows:
        sp, d = r["spread"], r["date"]
        if sp in open_until and d < open_until[sp]:
            continue  # still holding this spread — no re-entry

        resid_std = float(r.get("resid_std") or 0.0)
        sigma = realized_vol(sp, d) or resid_std    # risk anchor = realized vol
        z = float(r["z"])
        entry = float(r["actual"])
        fair = float(r["fair"])
        direction = "LONG" if r["direction"] == "BUY" else "SHORT"

        # === The fix ===
        # Walk this trade forward through the daily spread path using the live
        # tuned exit rule. Returns {close_reason, exit_price, exit_date,
        # hold_days, realised_pnl (per spread unit)} or None if the path or
        # forward window is incomplete.
        path = paths.get(sp)
        sim = (
            exit_sim.simulate_one(
                r,
                path,
                max_hold=exit_sim.MAX_HOLD,                  # 20 trading days
                sl_mult=live_ranker.TUNED_SL_MULT,           # 2.5
                tp_frac=live_ranker.TUNED_TP_FRAC,           # 0.5 — halfway to fair
            )
            if path is not None else None
        )
        if sim is None:
            # Tape edge (no full 20-day forward) — fall back to the raw 20-day
            # horizon move and label it honestly as a time-stop.
            exit_px = entry + float(r["fwd_move"])
            close_reason = "time_stop_20d"
            hold_days = exit_sim.MAX_HOLD
            pnl_bbl = float(r["fwd_pnl"])
            closed_at_iso = _iso(r["fwd_date"])
        else:
            exit_px = float(sim["exit_price"])
            close_reason = _CLOSE_REASON_MAP.get(sim["close_reason"], sim["close_reason"].lower())
            hold_days = int(sim["hold_days"])
            pnl_bbl = float(sim["realised_pnl"])             # already signed for direction
            closed_at_iso = _iso(str(sim["exit_date"]))

        reason_counts[close_reason] = reason_counts.get(close_reason, 0) + 1

        sd = size_trade(sp, sigma, z)
        barrels = sd.barrels
        realised = round(pnl_bbl * barrels, 2)               # real dollars
        dollar_risk = sd.dollar_risk or 1.0
        realised_pct = round(realised / dollar_risk * 100, 2)  # return on risk-at-stop

        # Display target & stop match what exit_sim ACTUALLY uses to close the
        # trade (and what the live engine in live_ranker.py uses), so the row
        # is self-consistent:
        #   • target = entry + TUNED_TP_FRAC × (anchor − entry)
        #     where anchor is p50 (model median), per exit_sim._tp_sl_for
        #   • stop   = entry ± TUNED_SL_MULT × resid_std (the model residual)
        # `sigma` (realized vol) is only used for risk-based sizing — that
        # separation is intentional (model resid_std is too thin for sizing;
        # see comment block above realized_vol).
        sign = 1.0 if direction == "LONG" else -1.0
        anchor = float(r.get("p50") if r.get("p50") is not None else fair)
        sl_sigma = resid_std if resid_std > 0 else sigma
        target = round(entry + live_ranker.TUNED_TP_FRAC * (anchor - entry), 4)
        stop = round(entry - sign * live_ranker.TUNED_SL_MULT * sl_sigma, 4)

        md = {
            "regime": r.get("regime"),
            "winner_model": r.get("winner"),
            "z": round(z, 3),
            "fair_value": round(fair, 4),
            "risk_sigma": round(sigma, 5),
            "resid_std": round(resid_std, 5),
            "lots": sd.lots,
            "dollar_risk": sd.dollar_risk,
            "tilt": sd.tilt,
            "sizing": sd.rationale,
            "track": "walkforward_oos",
            "hold_days": hold_days,
            "exit_kind": close_reason,
        }
        thesis = (
            f"{sp} {direction}: actual {entry:+.3f} vs fair {fair:+.3f} (z={z:+.2f}, "
            f"regime {r.get('regime')}, model {r.get('winner')}). {sd.lots} lots, "
            f"risk ${sd.dollar_risk:,.0f}. Exit: {close_reason} after {hold_days}d."
        )

        c.execute("""
            INSERT INTO paper_trades
              (asset, direction, size, entry_price, target_price, stop_price,
               opened_at, closed_at, exit_price, close_reason, status,
               source, conviction, thesis, mtm_price, mtm_at,
               unrealised, realised, realised_pct, metadata_json, ab_mode, ab_session)
            VALUES (?,?,?,?,?,?,?,?,?,?, 'CLOSED',
                    'walkforward', ?, ?, ?, ?, 0.0, ?, ?, ?, NULL, 'wf_backfill')
        """, (
            sp, direction, float(barrels), entry, target, stop,
            _iso(d), closed_at_iso, round(exit_px, 4), close_reason,
            _conviction(z), thesis, round(exit_px, 4), closed_at_iso,
            realised, realised_pct, json.dumps(md),
        ))
        # Track open-until — use the simulated exit date so re-entry rule
        # respects when the position actually closed (was the static fwd_date).
        open_until[sp] = str(sim["exit_date"]) if sim else r["fwd_date"]
        n += 1

    c.commit()
    c.close()
    return {"seeded": n, "window_start": cutoff, "window_end": last,
            "spreads": sorted(set(r["spread"] for r in rows)),
            "close_reason_counts": reason_counts}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--months", type=float, default=6.0)
    ap.add_argument("--reset", action="store_true")
    ap.add_argument("--include-wti", action="store_true",
                    help="include WTI spreads (synth/ESTIMATE data — off by default)")
    args = ap.parse_args()
    res = seed(months=args.months, reset=args.reset, brent_only=not args.include_wti)
    print(json.dumps(res, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
