"""
Phase 3.1 — live signal log.

The mentor's ask: "add a trade/signal log to the dashboard that records every
opportunity generated by the model, including timestamp, regime, instrument,
rationale, confidence score, and subsequent performance."

This module persists every actionable opportunity the live engine
(`live_engine.get_live_recommendation`) emits into a `signal_log` table in the
existing pulse_cache.db (same file as the paper book), and tracks each signal's
"subsequent performance" — how the spread moved after the signal fired — by
re-marking it against later live bars and resolving the tuned exit rule
(TP halfway-to-fair / SL 2.5σ / 30-trading-day time-stop), mirroring
live_ranker + paper_trading.

Idempotent: signals dedupe on (instrument, direction, feed_as_of, cadence), so
re-running a tick or firing daily + intraday jobs over the same bar won't
double-log.

Public API
----------
  generate_live_signals(*, cadence="daily", include_wti=False) → dict
      Run the live engine, persist each non-NEUTRAL opportunity, return a summary.
  update_signal_performance() → dict
      Mark every OPEN signal against the latest live spread value; resolve
      TP/SL/time-stop. Returns {checked, closed, still_open}.
  list_signals(status="all", limit=200) → list[dict]
  clear_signals(scope="all") → int
"""

from __future__ import annotations

import json
import logging
import os
import sqlite3
import sys
from datetime import datetime, timezone

_BACKEND = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if _BACKEND not in sys.path:
    sys.path.insert(0, _BACKEND)

log = logging.getLogger("pulse.research.signal_log")

_DB_PATH = os.path.join(_BACKEND, "db", "pulse_cache.db")


def _conn() -> sqlite3.Connection:
    c = sqlite3.connect(_DB_PATH, check_same_thread=False, timeout=5.0)
    # Mirror the WAL pragmas the paper book + cache use on the same file.
    c.execute("PRAGMA journal_mode=WAL")
    c.execute("PRAGMA busy_timeout=5000")
    c.execute("PRAGMA synchronous=NORMAL")
    c.row_factory = sqlite3.Row
    return c


def _ensure_table() -> None:
    c = _conn()
    try:
        c.execute("""
            CREATE TABLE IF NOT EXISTS signal_log (
                id            INTEGER PRIMARY KEY AUTOINCREMENT,
                signal_at     TEXT NOT NULL,      -- when we generated it (UTC wall clock)
                feed_as_of    TEXT,               -- live bar timestamp the signal was based on
                cadence       TEXT NOT NULL,      -- 'daily' | 'intraday'
                instrument    TEXT NOT NULL,      -- spread key (brent_m1_m2, ...)
                label         TEXT,
                regime        TEXT,
                regime_mode   TEXT,
                direction     TEXT NOT NULL,      -- BUY | SELL
                source        TEXT,               -- regime | baseline
                winner_model  TEXT,
                confidence    REAL,               -- engine confidence 0..1
                entry         REAL,               -- spread value at signal time
                fair_value    REAL,
                z_score       REAL,
                band_low      REAL,
                band_high     REAL,
                target        REAL,
                stop          REAL,
                notional_scale REAL,
                rationale     TEXT,
                -- subsequent performance (updated by update_signal_performance) --
                status        TEXT NOT NULL DEFAULT 'OPEN',   -- OPEN | CLOSED
                mtm_value     REAL,
                mtm_at        TEXT,
                mtm_move      REAL,               -- signed PnL in spread units (favourable +)
                close_value   REAL,
                closed_at     TEXT,
                close_reason  TEXT,               -- target | stop | time_stop | manual
                realised_move REAL,
                metadata_json TEXT,
                UNIQUE(instrument, direction, feed_as_of, cadence)
            )
        """)
        c.execute("CREATE INDEX IF NOT EXISTS idx_signal_status ON signal_log(status)")
        c.execute("CREATE INDEX IF NOT EXISTS idx_signal_at ON signal_log(signal_at)")
        c.commit()
    finally:
        c.close()


def _sign(direction: str) -> int:
    return 1 if direction == "BUY" else (-1 if direction == "SELL" else 0)


def _rationale(r: dict, regime: str) -> str:
    """Human-readable 'why' string from the engine receipts."""
    z = r.get("z_score")
    rich_cheap = "rich" if (z is not None and z > 0) else "cheap"
    fair = r.get("fair_value")
    cur = r.get("current")
    bits = [
        f"{regime} regime",
        f"{r.get('winner_model','?')} fair {fair} vs {cur}",
    ]
    if z is not None:
        bits.append(f"z={z:+.2f} ({abs(z):.1f}σ {rich_cheap})")
    src = r.get("recommendation_source")
    if src:
        bits.append(f"src={src}")
    drivers = r.get("drivers") or []
    if drivers:
        names = ", ".join(d.get("feature", d) if isinstance(d, dict) else str(d) for d in drivers[:3])
        bits.append(f"drivers: {names}")
    return " · ".join(bits)


def generate_live_signals(*, cadence: str = "daily", include_wti: bool = False) -> dict:
    """
    Run the live engine and persist every non-NEUTRAL opportunity it ranks.

    Idempotent on (instrument, direction, feed_as_of, cadence) — re-running over
    the same live bar inserts nothing new.
    """
    from research.live_engine import get_live_recommendation

    _ensure_table()
    rec = get_live_recommendation(include_wti=include_wti)
    if not rec.get("available"):
        return {"available": False, "error": rec.get("error"), "logged": 0}

    feed_as_of = rec.get("as_of_live") or (rec.get("live_feed") or {}).get("as_of")
    regime     = rec.get("regime")
    mode       = rec.get("regime_mode")
    now        = datetime.now(timezone.utc).isoformat(timespec="seconds")

    c = _conn()
    logged = 0
    skipped_neutral = 0
    try:
        for r in rec.get("ranked", []):
            direction = r.get("direction")
            if direction not in ("BUY", "SELL"):
                skipped_neutral += 1
                continue
            row = {
                "signal_at":      now,
                "feed_as_of":     feed_as_of,
                "cadence":        cadence,
                "instrument":     r.get("spread"),
                "label":          r.get("label"),
                "regime":         r.get("regime", regime),
                "regime_mode":    mode,
                "direction":      direction,
                "source":         r.get("recommendation_source"),
                "winner_model":   r.get("winner_model"),
                "confidence":     r.get("confidence"),
                "entry":          r.get("current"),
                "fair_value":     r.get("fair_value"),
                "z_score":        r.get("z_score"),
                "band_low":       r.get("band_low"),
                "band_high":      r.get("band_high"),
                "target":         r.get("target"),
                "stop":           r.get("stop"),
                "notional_scale": r.get("notional_scale", 1.0),
                "rationale":      _rationale(r, r.get("regime", regime)),
                "metadata_json":  json.dumps({
                    "r2_oos": r.get("r2_oos"), "n_train": r.get("n_train"),
                    "gate": r.get("gate"), "source_file": (rec.get("live_feed") or {}).get("source_file"),
                }),
            }
            cur = c.execute(
                """INSERT OR IGNORE INTO signal_log
                   (signal_at, feed_as_of, cadence, instrument, label, regime, regime_mode,
                    direction, source, winner_model, confidence, entry, fair_value, z_score,
                    band_low, band_high, target, stop, notional_scale, rationale, metadata_json)
                   VALUES
                   (:signal_at,:feed_as_of,:cadence,:instrument,:label,:regime,:regime_mode,
                    :direction,:source,:winner_model,:confidence,:entry,:fair_value,:z_score,
                    :band_low,:band_high,:target,:stop,:notional_scale,:rationale,:metadata_json)""",
                row,
            )
            if cur.rowcount:
                logged += 1
        c.commit()
    finally:
        c.close()

    return {
        "available":   True,
        "logged":      logged,
        "deduped":     len(rec.get("ranked", [])) - skipped_neutral - logged,
        "neutral":     skipped_neutral,
        "feed_as_of":  feed_as_of,
        "regime":      regime,
        "cadence":     cadence,
        "top":         (rec.get("top") or {}).get("label") if rec.get("top") else None,
    }


def update_signal_performance() -> dict:
    """
    Mark every OPEN signal against the latest live spread value (subsequent
    performance), and resolve the tuned exit rule:
      • target hit → close 'target'
      • stop hit   → close 'stop'
      • else update unrealised mtm_move and leave OPEN
    (Time-stop in trading days is handled by the scheduler/age check below.)

    mtm_move is signed so favourable moves are positive for BUY and SELL alike.
    """
    from research.live_feed   import get_live_snapshot
    from research.live_ranker import TUNED_MAX_HOLD_DAYS

    _ensure_table()
    # Current live spread values for both products (so already-logged WTI rows
    # still update even when new signals are Brent-only).
    live: dict[str, float] = {}
    for prod in ("CO", "CL"):
        snap = get_live_snapshot(prod)
        if snap.get("available"):
            for k, v in (snap.get("spreads") or {}).items():
                live[k] = v["value"]
            now_ts = snap.get("as_of")
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")

    c = _conn()
    checked = closed = still_open = 0
    try:
        rows = c.execute("SELECT * FROM signal_log WHERE status='OPEN'").fetchall()
        for s in rows:
            inst = s["instrument"]
            cur = live.get(inst)
            if cur is None:
                still_open += 1
                continue
            checked += 1
            sign = _sign(s["direction"])
            entry = s["entry"]
            mtm_move = round(sign * (cur - entry), 4) if entry is not None else None

            reason = None
            tgt, stp = s["target"], s["stop"]
            if s["direction"] == "BUY":
                if tgt is not None and cur >= tgt:   reason = "target"
                elif stp is not None and cur <= stp: reason = "stop"
            elif s["direction"] == "SELL":
                if tgt is not None and cur <= tgt:   reason = "target"
                elif stp is not None and cur >= stp: reason = "stop"

            # Time-stop: close after TUNED_MAX_HOLD_DAYS calendar-approx days.
            if reason is None:
                try:
                    opened = datetime.fromisoformat(s["signal_at"])
                    age_days = (datetime.now(timezone.utc) - opened).days
                    if age_days >= TUNED_MAX_HOLD_DAYS:
                        reason = "time_stop"
                except Exception:
                    pass

            if reason:
                c.execute(
                    """UPDATE signal_log SET status='CLOSED', mtm_value=?, mtm_at=?,
                       mtm_move=?, close_value=?, closed_at=?, close_reason=?, realised_move=?
                       WHERE id=?""",
                    (cur, now, mtm_move, cur, now, reason, mtm_move, s["id"]),
                )
                closed += 1
            else:
                c.execute(
                    "UPDATE signal_log SET mtm_value=?, mtm_at=?, mtm_move=? WHERE id=?",
                    (cur, now, mtm_move, s["id"]),
                )
                still_open += 1
        c.commit()
    finally:
        c.close()
    return {"checked": checked, "closed": closed, "still_open": still_open}


def list_signals(status: str = "all", limit: int = 200) -> list[dict]:
    _ensure_table()
    c = _conn()
    try:
        if status in ("OPEN", "CLOSED"):
            rows = c.execute(
                "SELECT * FROM signal_log WHERE status=? ORDER BY signal_at DESC, id DESC LIMIT ?",
                (status, limit),
            ).fetchall()
        else:
            rows = c.execute(
                "SELECT * FROM signal_log ORDER BY signal_at DESC, id DESC LIMIT ?",
                (limit,),
            ).fetchall()
        return [dict(r) for r in rows]
    finally:
        c.close()


def clear_signals(scope: str = "all") -> int:
    _ensure_table()
    c = _conn()
    try:
        if scope == "closed":
            cur = c.execute("DELETE FROM signal_log WHERE status='CLOSED'")
        else:
            cur = c.execute("DELETE FROM signal_log")
        c.commit()
        return cur.rowcount
    finally:
        c.close()


if __name__ == "__main__":
    # Windows console is cp1252 and chokes on the σ/× glyphs in the rationale;
    # stored values are UTF-8 (fine for the dashboard). Dev-print only.
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--cadence", default="daily", choices=("daily", "intraday"))
    ap.add_argument("--wti", action="store_true")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--update", action="store_true")
    ap.add_argument("--clear", action="store_true")
    args = ap.parse_args()

    if args.clear:
        print("cleared:", clear_signals())
    if not args.list and not args.update:
        print("generate:", json.dumps(generate_live_signals(cadence=args.cadence, include_wti=args.wti), indent=2))
    if args.update:
        print("perf update:", json.dumps(update_signal_performance(), indent=2))
    if args.list or not (args.update):
        print("\n=== signal_log ===")
        for s in list_signals():
            print(f"  [{s['signal_at']}] {s['instrument']:<14} {s['direction']:<4} "
                  f"conf={s['confidence']} z={s['z_score']} entry={s['entry']} "
                  f"status={s['status']} mtm_move={s['mtm_move']} reason={s['close_reason']}")
            print(f"      {s['rationale']}")
